from __future__ import annotations

from datetime import datetime
from typing import Protocol, runtime_checkable

from slskd_lidarr_bridge.domain.models import (
    AudioFile,
    DownloadJob,
    Release,
    SearchResponse,
    Transfer,
)


@runtime_checkable
class SoulseekGateway(Protocol):
    def start_search(self, text: str) -> str: ...
    def search_is_complete(self, search_id: str) -> bool: ...
    def search_responses(self, search_id: str) -> list[SearchResponse]: ...
    def enqueue(self, username: str, files: list[AudioFile]) -> None: ...
    def transfers(self, username: str) -> list[Transfer]: ...
    def cancel(self, username: str, transfer_id: str) -> None: ...
    def downloads_directory(self) -> str: ...  # slskd's completed-downloads dir


@runtime_checkable
class ReleaseStore(Protocol):
    def put(self, release: Release) -> str: ...  # returns assigned id
    def get(self, release_id: str) -> Release | None: ...
    def purge_older_than(self, cutoff: datetime) -> None: ...


@runtime_checkable
class JobStore(Protocol):
    def add(self, job: DownloadJob) -> None: ...
    def get(self, nzo_id: str) -> DownloadJob | None: ...
    def list(self) -> list[DownloadJob]: ...
    def remove(self, nzo_id: str) -> None: ...


@runtime_checkable
class Clock(Protocol):
    def now(self) -> datetime: ...
    def sleep(self, seconds: float) -> None: ...
